# Enable stateless CSRF protection for forms (submit only, not for login/logout)
framework:
    form:
        csrf_protection:
            token_id: submit

    csrf_protection:
        stateless_token_ids:
            - submit
