vich_uploader:
    db_driver: orm

    mappings:
        evenement:
            uri_prefix: /images/evenement
            upload_destination: '%kernel.project_dir%/public/images/evenement'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
